[project]
name = "xor-neural-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nexgen-neon", email = "ishaandas@globalids.com" }
]
requires-python = ">=3.14"
dependencies = [
    "panda>=0.3.1",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.0",
    "streamlit>=1.62.0",
    "torch>=2.14.0",
]

[project.scripts]
xor-neural-network = "xor_neural_network:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
